// Generated by gencpp from file pepper_training/QLearnElement.msg
// DO NOT EDIT!


#ifndef PEPPER_TRAINING_MESSAGE_QLEARNELEMENT_H
#define PEPPER_TRAINING_MESSAGE_QLEARNELEMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pepper_training/QLearnPoint.h>
#include <std_msgs/Float32.h>

namespace pepper_training
{
template <class ContainerAllocator>
struct QLearnElement_
{
  typedef QLearnElement_<ContainerAllocator> Type;

  QLearnElement_()
    : qlearn_point()
    , reward()  {
    }
  QLearnElement_(const ContainerAllocator& _alloc)
    : qlearn_point(_alloc)
    , reward(_alloc)  {
  (void)_alloc;
    }



   typedef  ::pepper_training::QLearnPoint_<ContainerAllocator>  _qlearn_point_type;
  _qlearn_point_type qlearn_point;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _reward_type;
  _reward_type reward;





  typedef boost::shared_ptr< ::pepper_training::QLearnElement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pepper_training::QLearnElement_<ContainerAllocator> const> ConstPtr;

}; // struct QLearnElement_

typedef ::pepper_training::QLearnElement_<std::allocator<void> > QLearnElement;

typedef boost::shared_ptr< ::pepper_training::QLearnElement > QLearnElementPtr;
typedef boost::shared_ptr< ::pepper_training::QLearnElement const> QLearnElementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pepper_training::QLearnElement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pepper_training::QLearnElement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pepper_training

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pepper_training': ['/home/marie/research_pepper/src/pepper_training/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pepper_training::QLearnElement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pepper_training::QLearnElement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_training::QLearnElement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_training::QLearnElement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_training::QLearnElement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_training::QLearnElement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pepper_training::QLearnElement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b8989080d174aa31a6bec6bc8011ef4";
  }

  static const char* value(const ::pepper_training::QLearnElement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b8989080d174aa3ULL;
  static const uint64_t static_value2 = 0x1a6bec6bc8011ef4ULL;
};

template<class ContainerAllocator>
struct DataType< ::pepper_training::QLearnElement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pepper_training/QLearnElement";
  }

  static const char* value(const ::pepper_training::QLearnElement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pepper_training::QLearnElement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pepper_training/QLearnPoint qlearn_point\n\
std_msgs/Float32 reward\n\
\n\
================================================================================\n\
MSG: pepper_training/QLearnPoint\n\
std_msgs/String state_tag\n\
std_msgs/Int32 action_number\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::pepper_training::QLearnElement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pepper_training::QLearnElement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.qlearn_point);
      stream.next(m.reward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QLearnElement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pepper_training::QLearnElement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pepper_training::QLearnElement_<ContainerAllocator>& v)
  {
    s << indent << "qlearn_point: ";
    s << std::endl;
    Printer< ::pepper_training::QLearnPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.qlearn_point);
    s << indent << "reward: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.reward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEPPER_TRAINING_MESSAGE_QLEARNELEMENT_H
