# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pepper_training/QLearnElement.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import pepper_training.msg
import std_msgs.msg

class QLearnElement(genpy.Message):
  _md5sum = "4b8989080d174aa31a6bec6bc8011ef4"
  _type = "pepper_training/QLearnElement"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """pepper_training/QLearnPoint qlearn_point
std_msgs/Float32 reward

================================================================================
MSG: pepper_training/QLearnPoint
std_msgs/String state_tag
std_msgs/Int32 action_number
================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: std_msgs/Int32
int32 data
================================================================================
MSG: std_msgs/Float32
float32 data"""
  __slots__ = ['qlearn_point','reward']
  _slot_types = ['pepper_training/QLearnPoint','std_msgs/Float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       qlearn_point,reward

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(QLearnElement, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.qlearn_point is None:
        self.qlearn_point = pepper_training.msg.QLearnPoint()
      if self.reward is None:
        self.reward = std_msgs.msg.Float32()
    else:
      self.qlearn_point = pepper_training.msg.QLearnPoint()
      self.reward = std_msgs.msg.Float32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.qlearn_point.state_tag.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_if().pack(_x.qlearn_point.action_number.data, _x.reward.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.qlearn_point is None:
        self.qlearn_point = pepper_training.msg.QLearnPoint()
      if self.reward is None:
        self.reward = std_msgs.msg.Float32()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.qlearn_point.state_tag.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.qlearn_point.state_tag.data = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.qlearn_point.action_number.data, _x.reward.data,) = _get_struct_if().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.qlearn_point.state_tag.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_if().pack(_x.qlearn_point.action_number.data, _x.reward.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.qlearn_point is None:
        self.qlearn_point = pepper_training.msg.QLearnPoint()
      if self.reward is None:
        self.reward = std_msgs.msg.Float32()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.qlearn_point.state_tag.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.qlearn_point.state_tag.data = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.qlearn_point.action_number.data, _x.reward.data,) = _get_struct_if().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_if = None
def _get_struct_if():
    global _struct_if
    if _struct_if is None:
        _struct_if = struct.Struct("<if")
    return _struct_if
